apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.resource_group_name}}
  annotations:
    github.com/project-slug: 'RohanAwasthi/CIL Integration'
    jenkins.io/github-folder: 'new-folder/${{ parameters.resource_group_name }}'
  description: Resource group creation by backstage
  tags:
    - azure
    - terraform
spec:
  type: service
  system: Azure
  lifecycle: experimental
  owner: guests
