apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gke-cluster-devex
  annotations:
    github.com/project-slug: RohanAwasthi/GCP-Cluster
  description: GCP gke cluster managed by Terraform
  tags:
    - gcp
    - gke
    - terraform
spec:
  type: service
  system: GCP
  lifecycle: experimental
  owner: guests
