apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gcp-gke-template
  annotations:
    github.com/project-slug: RohanAwasthi/GCP-Cluster
  description: GCP gke cluster managed by Terraform
  tags:
    - aws
    - eks
    - terraform
spec:
  type: service
  lifecycle: experimental
  owner: guests
