apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.project | dump}}
  annotations:
    github.com/project-slug: RohanAwasthi/GCP-Cluster
  description: GCP gke cluster managed by Terraform
  tags:
    - gcp
    - gke
    - terraform
spec:
  type: service
  lifecycle: experimental
  owner: guests
