apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.container_cluster_name }}
  annotations:
    github.com/project-slug: RohanAwasthi/GCP-Cluster
    jenkins.io/github-folder: 'gcp-gke-cluster/${{ values.container_cluster_name }}'
  description: ${{values.description | dump}}
  tags:
    - gcp
    - gke
    - terraform
spec:
  type: service
  system: GCP
  lifecycle: experimental
  owner: guests
