apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  labels:
    system: web-apps
    trackid: aws-apache-web-app-20231005140155
  links:
    - url: https://github.com/ItRachii/aws-apache-web-app
      title: ${{values.component_id | dump}}
      icon: code
  tags:
    - java
    - aws
    - applicationtype-webapplication
  annotations:
    jenkins.io/github-folder: 'apache-aws-web-app/${{values.component_id}}'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: 'ItRachii/aws-apache-web-app'
    sonarqube.org/project-key: 'JtSpringProject/rachit'
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  ownerEmail: ${{values.ownerEmail}}
