create_resource_group : true
resource_group_name   : "cloudifyrgmit"
location              : "South India"
tags : 
  Project_ID          : "Cloudify"
  Owner               : "mitali.ghoshal@gds.ey.com"