create_resource_group : true
resource_group_name   : "cloudifyrgmit"
location              : "South India"
tags : 
  Project_ID : "CLOUDIFY"

public_ip_name        : "pip123"
allocation_method     : "Static"

#properties below are optional 
sku                     : "Standard" #defaults to Basic
ip_version              : "IPv4"     #defaults to IP4, Only dynamic for IPv6, Supported arguments are IPv4 or IPv6, NOT Both
domain_name_label       : "testip-dns"
idle_timeout_in_minutes : 5
### refer to the prefix and check sku types are same in IP and prefix
sku_tier                : "Regional"
ddos_protection_mode    : "Disabled" #Defaults to VirtualNetworkInherited
ddos_protection_plan_id : null       #ddos_protection_plan_id can only be set when ddos_protection_mode is Enabled