
# Define the API version and kind of resource
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# Template metadata. Here's your intro to what this template does.
metadata:
  name: gke-cluster
  title: GCP GKE Cluster
  description: Deploy GCP GKE Cluster using Terraform
# The specification for how the template behaves
spec:
  # Who owns this template. Generally, it could be a team or individual
  owner: user:guest
  # The type of service this template deploys
  type: service
  # User-input parameters. Makes your templates dynamic!
  parameters:
    # Ask the user to input some basic app details
    - title: Provide Details
      required:
        - project
      properties:
        project:
          title: Project ID
          type: string
          description: Unique name for your project
          ui:autofocus: true  # This field gets auto-focused in UI
          ui:options:
            rows: 5  # Number of rows in the input area
    # Ask the user where they want to store the code
    - title: Choose a Repo location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker  # A special UI component for selecting repo URLs
          ui:options:
            allowedHosts:
              - github.com  # Allowed hosts for repository
    # Parameters for setting up the EKS cluster
    - title: Basic GKE Cluster Configuration
      required:
        - container_cluster_name
        - location
        - description
      properties:
        container_cluster_name:
          title: Cluster Name
          type: string
          description: The name of your GKE cluster
          ui:autofocus: true
        location:
          title: Location
          type: string
          description: The GCP location where the cluster will be deployed
          enum:
            - us-central1
            - us-central2
        description:
          title: Description
          type: string
          description: Description of the project
          ui:autofocus: true
  steps:
    - id: template
      name: Fetching Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          project: ${{ parameters.project }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          #owner: ${{ parameters.owner }}
          container_cluster_name: ${{ parameters.container_cluster_name }}
          application_name: ${{ parameters.application_name }}
          location: ${{ parameters.location }}
          #track_id: ${{ parameters.track_id }}

    - id: publish
      name: Publishing to GitHub
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.project }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public
        defaultBranch: main

    - id: webhook
      name: Adding webhook to Github Respository
      action: github:webhook
      input: 
        repoUrl: ${{ parameters.repoUrl }}
        webhookUrl: http://10.1.0.228:8080/github-webhook/
        #webhookUrl: http://172.190.72.81:8080/github-webhook/
        events:
        - push
        active: true
        contentType: json 

    - id: jenkinsJob
      name: create jenkins Job
      action: jenkins:job:create
      input:
        component_id: ${{ parameters.project }}
        allowedHosts: ['github.com']
        # description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        folder: "gcp-gke-cluster"
        job: 'int-devops-cloud-0224'
       # track_id: ${{ parameters.track_id }}
        
    # - id: sonarJenkinsJob
    #   name: create code quality jenkins Job
    #   action: jenkins:job:createSonar
    #   input:
    #     component_id: ${{ parameters.component_id }}
    #     allowedHosts: ['github.com']
    #     # description: This is ${{ parameters.name }}
    #     repoUrl: ${{ parameters.repoUrl }}
    #     folder: "custom-actions"
    #     job: 'Sonar${{ parameters.component_id }}'
    #     track_id: ${{ parameters.track_id }}


    - id: jenkinsRun
      name: Run Jenkins Job
      action: jenkins:job:run
      input:
        component_id: ${{ parameters.project }}
        allowedHosts: ['github.com']
        # description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        folder: "gcp-gke-cluster"
        job: 'int-devops-cloud-0224'

    # - id: jenkinsRunSonar
    #   name: Run Code Quality Jenkins Job
    #   action: jenkins:job:runSonar
    #   input:
    #     component_id: ${{ parameters.component_id }}
    #     allowedHosts: ['github.com']
    #     # description: This is ${{ parameters.name }}
    #     repoUrl: ${{ parameters.repoUrl }}
    #     folder: "custom-actions"
    #     job: 'Sonar${{ parameters.component_id }}'

    - id: register
      name: Registering Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
 
