apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  labels:
    system: web-apps
  links:
    - url: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}
      title: ${{values.component_id | dump}}
      icon: code
  tags:
    - java
    - azure
    - applicationtype-webapplication
  annotations:
    jenkins.io/github-folder: 'apache-web-app/azure-terrform-job'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug:  ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/linguist: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}
    azure.com/tag-selector: pid/p44
spec:
  type: service
  lifecycle: development
  system: azure cloud
  owner: ${{ values.owner }}
